service: serverless-crud

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1
  stage: dev

functions:
  create:
    handler: handler.create
    events:
      - http:
          path: todos
          method: post
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
          authorizer: arn:aws:lambda:us-east-1:957571668058:function:serverless-authentication-dev-authorize
  readAll:
    handler: handler.readAll
    events:
      - http:
          path: todos
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
          authorizer: arn:aws:lambda:us-east-1:957571668058:function:serverless-authentication-dev-authorize
  readOne:
    handler: handler.readOne
    events:
      - http:
          path: todos/{id}
          method: get
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
          authorizer: arn:aws:lambda:us-east-1:957571668058:function:serverless-authentication-dev-authorize

  update:
    handler: handler.update
    events:
      - http:
          path: todos/{id}
          method: put
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
          authorizer: arn:aws:lambda:us-east-1:957571668058:function:serverless-authentication-dev-authorize

  delete:
    handler: handler.delete
    events:
      - http:
          path: todos/{id}
          method: delete
          cors:
            origins:
              - '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
            allowCredentials: true
          authorizer: arn:aws:lambda:us-east-1:957571668058:function:serverless-authentication-dev-authorize
